//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargos
    {
        public cargos()
        {
            this.funcionarios = new HashSet<funcionarios>();
        }
    
        public int IDCARGO { get; set; }
        public string CARGO { get; set; }
    
        public virtual ICollection<funcionarios> funcionarios { get; set; }
    }
}
