//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratosinistros
    {
        public int IDCONTRATOSINISTROS { get; set; }
        public int CONTRATOCARRO_IDCONTRATOCARRO { get; set; }
        public string DESCRIÃ_ÃƒO { get; set; }
        public decimal VALOR { get; set; }
    
        public virtual contratocarro contratocarro { get; set; }
    }
}
