//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public endereco()
        {
            this.cliente = new HashSet<cliente>();
            this.motoristas = new HashSet<motoristas>();
        }
    
        public int IDENDERECO { get; set; }
        public string TIPO { get; set; }
        public string CEP { get; set; }
        public string LOGRADOURO { get; set; }
        public Nullable<int> NUM { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<motoristas> motoristas { get; set; }
    }
}
