//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelos
    {
        public modelos()
        {
            this.carros = new HashSet<carros>();
        }
    
        public int IDMODELO { get; set; }
        public int MONTADORA_IDMONTADORA { get; set; }
        public string NOME { get; set; }
    
        public virtual ICollection<carros> carros { get; set; }
        public virtual montadora montadora { get; set; }
    }
}
