//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class montadora
    {
        public montadora()
        {
            this.modelos = new HashSet<modelos>();
        }
    
        public int IDMONTADORA { get; set; }
        public string NOME { get; set; }
    
        public virtual ICollection<modelos> modelos { get; set; }
    }
}
