//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratoviagens
    {
        public int IDCONTRATOVIAGENS { get; set; }
        public int CONTRATO_IDCONTRATO { get; set; }
        public string ROTA { get; set; }
        public Nullable<int> OCUPANTES { get; set; }
    
        public virtual contratocarro contratocarro { get; set; }
    }
}
