//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratocarro
    {
        public contratocarro()
        {
            this.carros = new HashSet<carros>();
            this.contratopneus = new HashSet<contratopneus>();
            this.contratoseguros = new HashSet<contratoseguros>();
            this.contratosinistros = new HashSet<contratosinistros>();
            this.contratoviagens = new HashSet<contratoviagens>();
            this.motoristas = new HashSet<motoristas>();
            this.multas = new HashSet<multas>();
        }
    
        public int IDCONTRATOCARRO { get; set; }
        public int CONTRATOS_IDCONTRATO { get; set; }
        public int CARRO_IDCARRO { get; set; }
    
        public virtual ICollection<carros> carros { get; set; }
        public virtual carros carros1 { get; set; }
        public virtual contratos contratos { get; set; }
        public virtual ICollection<contratopneus> contratopneus { get; set; }
        public virtual ICollection<contratoseguros> contratoseguros { get; set; }
        public virtual ICollection<contratosinistros> contratosinistros { get; set; }
        public virtual ICollection<contratoviagens> contratoviagens { get; set; }
        public virtual ICollection<motoristas> motoristas { get; set; }
        public virtual ICollection<multas> multas { get; set; }
    }
}
