//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratos
    {
        public contratos()
        {
            this.contratocarro = new HashSet<contratocarro>();
            this.pneus = new HashSet<pneus>();
        }
    
        public int IDCONTRATO { get; set; }
        public int CLIENTE_IDCLIENTE { get; set; }
        public Nullable<sbyte> STATUS { get; set; }
        public System.DateTime DATACONTRATO { get; set; }
        public Nullable<System.DateTime> DATAINICIO { get; set; }
        public Nullable<System.DateTime> DATAFINAL { get; set; }
        public decimal VALOR { get; set; }
        public int KMINICIAL { get; set; }
        public int KMFINAL { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<contratocarro> contratocarro { get; set; }
        public virtual ICollection<pneus> pneus { get; set; }
    }
}
