//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionarios
    {
        public int IDFUNCIONARIO { get; set; }
        public int CARGOS_IDCARGO { get; set; }
        public int USUARIOS_IDUSUARIO { get; set; }
        public int MATRICULA { get; set; }
        public string NOME { get; set; }
		public string EMAIL { get; set; }
		public decimal SALARIO { get; set; }
		public int CPF { get; set; }
		public int RG { get; set; }
		public int PIS { get; set; }
		public int CTPS { get; set; }
		public int TITELEITOR { get; set; }
		public string NASCIMENTO { get; set; }
		public string CEP { get; set; }
        public string LOGRADOURO { get; set; }
        public string NUM { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string TELCEL { get; set; }
        public string TELRES { get; set; }
		public DateTime ADMISSAO { get; set; }
		public DateTime DEMISSAO { get; set; }

		public virtual cargos cargos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
