//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fatcarEntities : DbContext
    {
        public fatcarEntities()
            : base("name=fatcarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cargos> cargos { get; set; }
        public DbSet<carros> carros { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<contratocarro> contratocarro { get; set; }
        public DbSet<contratopneus> contratopneus { get; set; }
        public DbSet<contratos> contratos { get; set; }
        public DbSet<contratoseguros> contratoseguros { get; set; }
        public DbSet<contratosinistros> contratosinistros { get; set; }
        public DbSet<contratoviagens> contratoviagens { get; set; }
        public DbSet<cor> cor { get; set; }
        public DbSet<endereco> endereco { get; set; }
        public DbSet<entradasaida> entradasaida { get; set; }
        public DbSet<funcionarios> funcionarios { get; set; }
        public DbSet<manutencao> manutencao { get; set; }
        public DbSet<manutencaopeca> manutencaopeca { get; set; }
        public DbSet<modelos> modelos { get; set; }
        public DbSet<montadora> montadora { get; set; }
        public DbSet<motoristas> motoristas { get; set; }
        public DbSet<multas> multas { get; set; }
        public DbSet<pecas> pecas { get; set; }
        public DbSet<pneus> pneus { get; set; }
        public DbSet<telefonecliente> telefonecliente { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
