//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class motoristas
    {
        public int IDMOTORISTAS { get; set; }
        public int CONTRATOCARRO_IDCONTRATOCARRO { get; set; }
        public int ENDERECO_IDENDERECO { get; set; }
        public string NOME { get; set; }
        public string CNH { get; set; }
        public string VALIDADE { get; set; }
        public string CATEGORIA { get; set; }
    
        public virtual contratocarro contratocarro { get; set; }
        public virtual endereco endereco { get; set; }
    }
}
