//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class pecas
    {
        public pecas()
        {
            this.manutencaopeca = new HashSet<manutencaopeca>();
        }
    
        public int IDPECA { get; set; }
        public string DESCRICAO_PECA { get; set; }
        public decimal VALOR_PECA { get; set; }
    
        public virtual ICollection<manutencaopeca> manutencaopeca { get; set; }
    }
}
