//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class pneus
    {
        public int IDPNEUS { get; set; }
        public int CARROS_IDCARROS { get; set; }
        public string TIPOPNEU { get; set; }
        public int KMINICIAL { get; set; }
        public int KMATUAL { get; set; }
    
        public virtual contratos contratos { get; set; }
    }
}
