//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.cliente = new HashSet<cliente>();
            this.funcionarios = new HashSet<funcionarios>();
        }
    
        public int IDUSUARIO { get; set; }
        public int NIVEL { get; set; }
        public string LOGIN { get; set; }
        public string PASS { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<funcionarios> funcionarios { get; set; }
    }
}
